Initial version of brp-mangle-shebangs

diff --git a/brpscripts/Fedora/brp-mangle-shebangs b/brpscripts/Fedora/brp-mangle-shebangs
--- a/brpscripts/Fedora/brp-mangle-shebangs
+++ b/brpscripts/Fedora/brp-mangle-shebangs
@@ -1,12 +1,9 @@
-#!/bin/bash -eu
+#!/bin/sh -eu
 
 # If using normal root, avoid changing anything.
 if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
   exit 0
 fi
-
-exclude_files="${1:-}"
-exclude_shebangs="${2:-}"
 
 cd "$RPM_BUILD_ROOT"
 
@@ -15,31 +12,18 @@ trim() {
 }
 
 fail=0
-while IFS= read -r -d $'\0' f; do
-  file -N --mime-type "$f" | grep -q -P ".+(?=: text/)" || continue
-
-  # Remove the dot
-  path="${f#.}"
-
-  if [ -n "$exclude_files" ]; then
-    echo "$path" | grep -q -E "$exclude_files" && continue
-  fi
+for f in $(find -executable -type f | xargs --no-run-if-empty file -N --mime-type | grep -Po "^\K.+(?=: text/)"); do
 
   ts=$(stat -c %y "$f")
 
-  read shebang_line < "$f" || :
-  orig_shebang=$(trim $(echo "$shebang_line" | grep -Po "#!\K.*" || echo))
-  shebang="$orig_shebang"
-  if [ -n "$exclude_shebangs" ]; then
-    echo "$shebang" | grep -q -E "$exclude_shebangs" && continue
-  fi
-
+  read orig_shebang < "$f" || :
+  shebang=$(trim $(echo "$orig_shebang" | grep -Po "#!\K.*" || echo))
   if [ -z "$shebang" ]; then
     echo >&2 "*** WARNING: $f is executable but has empty or no shebang, removing executable bit"
     chmod -x "$f"
     touch -d "$ts" "$f"
     continue
-  elif [ -n "${shebang##/*}" ]; then
+  elif [ "${shebang%${shebang#?}}" != "/" ]; then
     echo >&2 "*** ERROR: $f has shebang which doesn't start with '/' ($shebang)"
     fail=1
     continue
@@ -50,8 +34,6 @@ while IFS= read -r -d $'\0' f; do
   fi
 
   # Replace "special" env shebang:
-  # /whatsoever/env /whatever/foo → /whatever/foo
-  shebang=$(echo "$shebang" | sed -r -e 's@^(.+)/env /(.+)$@/\2@')
   # /whatsoever/env foo → /whatsoever/foo
   shebang=$(echo "$shebang" | sed -r -e 's@^(.+/)env (.+)$@\1\2@')
 
@@ -60,13 +42,13 @@ while IFS= read -r -d $'\0' f; do
 
   if [ "$shebang" != "$py_shebang" ]; then
     sed -i -e "1c #!$py_shebang" "$f"
-    echo >&2 "*** WARNING: mangling shebang in $path from #!$orig_shebang to #!$py_shebang. This will become an ERROR, fix it manually!"
-  elif [ "#!$shebang" != "#!$orig_shebang" ]; then
+    echo >&2 "*** WARNING: mangling shebang in $f from $orig_shebang to #!$py_shebang. This will become an ERROR, fix it manually!"
+  elif [ "#!$shebang" != "$orig_shebang" ]; then
     sed -i -e "1c #!$shebang" "$f"
-    echo "mangling shebang in $path from $orig_shebang to #!$shebang"
+    echo "mangling shebang in $f from $orig_shebang to #!$shebang"
   fi
 
   touch -d "$ts" "$f"
-done < <(find -executable -type f -print0)
+done
 
 exit $fail
